### DISCUSSION TITLE
Can all pv use the same subdirectory?

### DISCUSSION THREAD

**Discussion by huanghantao** [kubernetes-csi/csi-driver-nfs#348] [Q&A] [answered]
These are my YAML files:

```yaml
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: nfs-server.default.svc.cluster.local
  share: /
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pv1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
  storageClassName: nfs-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pv2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
  storageClassName: nfs-csi
```

It creates two pv using different subdirectories as shown below:

<img width="305" alt="image" src="https://user-images.githubusercontent.com/22836925/172790411-68e2336a-3ce7-4201-a1bf-c9d8b852354f.png">

Is there a way to create pv using the same directory as shown below:

<img width="308" alt="image" src="https://user-images.githubusercontent.com/22836925/172790702-e0617549-16bd-49b2-ad48-59c744cb921c.png">

Also, I wish the `/cache-image` directory had been created by CSI for me, not by me.

**Comment by andyzhangx** [comment, marked as answer]
then I think you could use one PV/PVC pair, and the PVC could be used by multiple pods

**Reply by huanghantao** [reply]
Yes, I can create a PV statically, maybe I need to create a pod to create subdirectory

**Reply by andyzhangx** [reply]
the subdirectory created by this driver is a uuid, cannot be specified now, I think that's two questions:
1) use one PVC (shared by multiple pods), and uuid sub dir would be created by the driver (dynamic way)
2) specify subDir name in storage class: it's a feature request, not supported yet

**Reply by huanghantao** [reply]
> the subdirectory created by this driver is a uuid, cannot be specified now, I think that's two questions:
> 
> 1. use one PVC (shared by multiple pods), and uuid sub dir would be created by the driver (dynamic way)
> 2. specify subDir name in storage class: it's a feature request, not supported yet

Is it possible to support specific subdirectories? Because here we have a scenario where the entire cluster needs to use the same directory to cache all the base images needed for kaniko's build.

**Reply by huanghantao** [reply]
The name of this subdirectory could also be uuid, but I want to create PVS that use the same subdirectory

**Reply by andyzhangx** [reply]
then you could just create a PVC, and let the driver create uuid subdir, it should work, here is an example: https://github.com/kubernetes-csi/csi-driver-nfs/blob/master/deploy/example/pvc-nfs-csi-dynamic.yaml, all pods should reference that PVC.

**Reply by huanghantao** [reply]
Because we are a multi-tenant system, all PVCS under namespaces want to use the same subdirectory

**Reply by andyzhangx** [reply]
sure, let me check how to support this feature: `specify subDir name in storage class`

**Reply by huanghantao** [reply]
thank you！

**Reply by andyzhangx** [reply]
should be fixed by https://github.com/kubernetes-csi/csi-driver-nfs/pull/349, could you try the master branch with image: `gcr.io/k8s-staging-sig-storage/nfsplugin:canary`

**Reply by andyzhangx** [reply]
add a new parameter in storage class: 
```
parameters:
  server: nfs-server.default.svc.cluster.local
  share: /
  subDir: "xxx"
```
