### DISCUSSION TITLE
How to backup and restore between different namespaces ?

### DISCUSSION THREAD

**Discussion by jackchuong** [kubernetes-csi/csi-driver-nfs#524] [Q&A]
Hi all.
I have internal K8S cluster (build by K3S)
1 default storageclass csi-driver-nfs install by Helm3, I have 1 QNAP NAS device as NFS server
This is my StorageClass and VolumeSnapshotClass
```
---
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storageclass-csi-nfs-sgnnas03
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: nfs.csi.k8s.io
parameters:
  server: "192.168.7.107"
  share: /k8s-nfs-sgnnas03
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: csi-nfs-snapclass
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
driver: nfs.csi.k8s.io
deletionPolicy: Delete
```
What is detail steps to snapshot a dynamic pvcA from namespace A then restore to a pvcB at namespace B ?
I tried:
- create volumesnapshot of pvcA at namespace A
```
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: ocs-snapshot
  namespace: ocs-inventory
spec:
  volumeSnapshotClassName: csi-nfs-snapclass
  source:
    persistentVolumeClaimName: ocs-pvc
```
--> it creates folder "snapcontent-e382491c-1c12-4fd2-a513-2ed5ee7060a0" with file "pvc-4ff12ffb-e929-4862-8500-078d13041d1c.tar.gz" at nfs server share
```
kubectl -n ocs-inventory get pvc,volumesnapshot,volumesnapshotcontent
NAME                            STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                    AGE
persistentvolumeclaim/ocs-pvc   Bound    pvc-4ff12ffb-e929-4862-8500-078d13041d1c   10Gi       RWX            storageclass-csi-nfs-sgnnas03   5d4h

NAME                                                  READYTOUSE   SOURCEPVC   SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAPSHOTCLASS       SNAPSHOTCONTENT                                    CREATIONTIME   AGE
volumesnapshot.snapshot.storage.k8s.io/ocs-snapshot   true         ocs-pvc                             208622773     csi-nfs-snapclass   snapcontent-e382491c-1c12-4fd2-a513-2ed5ee7060a0   12m            15m

NAME                                                                                             READYTOUSE   RESTORESIZE   DELETIONPOLICY   DRIVER           VOLUMESNAPSHOTCLASS   VOLUMESNAPSHOT   VOLUMESNAPSHOTNAMESPACE   AGE
volumesnapshotcontent.snapshot.storage.k8s.io/snapcontent-e382491c-1c12-4fd2-a513-2ed5ee7060a0   true         208622773     Retain           nfs.csi.k8s.io   csi-nfs-snapclass     ocs-snapshot     ocs-inventory             15m
```

- delete above volumesnapshot and volumesnapshotcontent.
- create pre-provisioned volumesnapshotcontent name "snapcontent-e382491c-1c12-4fd2-a513-2ed5ee7060a0"
- create snapshotvolume link to new volumesnapshotcontent
- create pvcB in namespace B with source from new snapshotvolume
```
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  name: snapcontent-e382491c-1c12-4fd2-a513-2ed5ee7060a0
spec:
  deletionPolicy: Retain
  driver: nfs.csi.k8s.io
  source:
    snapshotHandle: 192.168.7.107#k8s-nfs-sgnnas03#snapshot-e382491c-1c12-4fd2-a513-2ed5ee7060a0#snapshot-e382491c-1c12-4fd2-a513-2ed5ee7060a0#pvc-4ff12ffb-e929-4862-8500-078d13041d1c
  volumeSnapshotClassName: csi-nfs-snapclass
  volumeSnapshotRef:
    apiVersion: snapshot.storage.k8s.io/v1
    kind: VolumeSnapshot
    name: restore-snapshot
    namespace: restore
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: restore-snapshot
  namespace: restore
spec:
  volumeSnapshotClassName: csi-nfs-snapclass
  source:
    volumeSnapshotContentName: snapcontent-e382491c-1c12-4fd2-a513-2ed5ee7060a0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restore-pvc
  namespace: restore
spec:
  storageClassName: storageclass-csi-nfs-sgnnas03
  dataSource:
    name: restore-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
```
But new volumesnapshotcontent and snapshotvolume have RESTORESIZE=0 , so pvcB keep pending...
```
kubectl -n restore get pvc,volumesnapshot,volumesnapshotcontent
NAME                                STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS                    AGE
persistentvolumeclaim/restore-pvc   Pending                                      storageclass-csi-nfs-sgnnas03   8s

NAME                                                      READYTOUSE   SOURCEPVC   SOURCESNAPSHOTCONTENT                              RESTORESIZE   SNAPSHOTCLASS       SNAPSHOTCONTENT                                    CREATIONTIME   AGE
volumesnapshot.snapshot.storage.k8s.io/restore-snapshot   true                     snapcontent-e382491c-1c12-4fd2-a513-2ed5ee7060a0   0             csi-nfs-snapclass   snapcontent-e382491c-1c12-4fd2-a513-2ed5ee7060a0   4m16s          90s

NAME                                                                                             READYTOUSE   RESTORESIZE   DELETIONPOLICY   DRIVER           VOLUMESNAPSHOTCLASS   VOLUMESNAPSHOT     VOLUMESNAPSHOTNAMESPACE   AGE
volumesnapshotcontent.snapshot.storage.k8s.io/snapcontent-e382491c-1c12-4fd2-a513-2ed5ee7060a0   true         0             Retain           nfs.csi.k8s.io   csi-nfs-snapclass     restore-snapshot   restore                   4m16s
```

Please give me some adivce, thank you very much.

**Comment by andyzhangx** [comment]
we have increased the snapshot timeout as 20min in this PR: https://github.com/kubernetes-csi/csi-driver-nfs/pull/512, `RESTORESIZE=0` issue could be due to small snapshot timeout issue, similar issue: https://github.com/kubernetes-csi/csi-driver-nfs/issues/509

**Reply by jackchuong** [reply]
How can I increase the snapshot timeout ?
```
kubectl -n nfs-provisioner get deploy
NAME                  READY   UP-TO-DATE   AVAILABLE   AGE
snapshot-controller   1/1     1            1           23d
csi-nfs-controller    1/1     1            1           23d
```
I tried `kubectl -n nfs-provisioner edit deploy/snapshot-controller` to add - --timeout=30m into args but it doest let me.
I tried helm uninstall , helm repo update , helm install again but it doesn;t get new csi-nfs-controller template

**Reply by andyzhangx** [reply]
```
kubectl edit -n nfs-provisioner csi-nfs-controller 
```

and then append `- "--timeout=1200s"` in `csi-provisioner` and `csi-snapshotter`

https://github.com/kubernetes-csi/csi-driver-nfs/pull/512/files

**Reply by jackchuong** [reply]
When I edit deploy/csi-nfs-controller I can see that `csi-provisioner` and` csi-snapshotter` have `- "--timeout=1200s"` already , maybe Helm repo update worked, I'm reproducing above steps, will feedback result later

**Reply by jackchuong** [reply]
the volumesnapshotcontent's READYTOUSE is false and RESTORESIZE is null after 76m
```
kubectl -n restore get volumesnapshotcontent
NAME                                               READYTOUSE   RESTORESIZE   DELETIONPOLICY   DRIVER           VOLUMESNAPSHOTCLASS   VOLUMESNAPSHOT     VOLUMESNAPSHOTNAMESPACE   AGE
snapcontent-e382491c-1c12-4fd2-a513-2ed5ee7060a0   false                      Retain           nfs.csi.k8s.io   csi-nfs-snapclass     restore-snapshot   restore                   76m
```

**Reply by andyzhangx** [reply]
@jackchuong could you check the nfs controller logs: https://github.com/kubernetes-csi/csi-driver-nfs/blob/master/docs/csi-debug.md#case1-volume-createdelete-failed

**Reply by jackchuong** [reply]
```
kubectl -n nfs-provisioner get pod
NAME                                   READY   STATUS    RESTARTS   AGE
snapshot-controller-7c47788447-z4qlv   1/1     Running   0          167m
csi-nfs-node-6bs56                     3/3     Running   0          167m
csi-nfs-controller-59b69c85cc-j554z    4/4     Running   0          167m
```

```
kubectl -n nfs-provisioner describe pod csi-nfs-controller-59b69c85cc-j554z
Name:                 csi-nfs-controller-59b69c85cc-j554z
Namespace:            nfs-provisioner
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Service Account:      csi-nfs-controller-sa
Node:                 k3s-hq-master1/192.168.7.200
Start Time:           Wed, 18 Oct 2023 17:26:28 +0700
Labels:               app=csi-nfs-controller
                      app.kubernetes.io/instance=csi-driver-nfs
                      app.kubernetes.io/managed-by=Helm
                      app.kubernetes.io/name=csi-driver-nfs
                      app.kubernetes.io/version=v4.4.0
                      helm.sh/chart=csi-driver-nfs-v4.4.0
                      pod-template-hash=59b69c85cc
Annotations:          <none>
Status:               Running
SeccompProfile:       RuntimeDefault
IP:                   192.168.7.200
IPs:
  IP:           192.168.7.200
Controlled By:  ReplicaSet/csi-nfs-controller-59b69c85cc
Containers:
  csi-provisioner:
    Container ID:  containerd://a352bd75f4ed96e2b2dbc50075798a061b636543254fd0846d51d1c9cd5c2066
    Image:         registry.k8s.io/sig-storage/csi-provisioner:v3.5.0
    Image ID:      registry.k8s.io/sig-storage/csi-provisioner@sha256:d078dc174323407e8cc6f0f9abd4efaac5db27838f1564d0253d5e3233e3f17f
    Port:          <none>
    Host Port:     <none>
    Args:
      -v=2
      --csi-address=$(ADDRESS)
      --leader-election
      --leader-election-namespace=nfs-provisioner
      --extra-create-metadata=true
      --timeout=1200s
    State:          Running
      Started:      Wed, 18 Oct 2023 17:26:30 +0700
    Ready:          True
    Restart Count:  0
    Limits:
      memory:  400Mi
    Requests:
      cpu:     10m
      memory:  20Mi
    Environment:
      ADDRESS:  /csi/csi.sock
    Mounts:
      /csi from socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-fgqfl (ro)
  csi-snapshotter:
    Container ID:  containerd://eca10c2be63cbec2b5b080e6b05880727f5601c0b357531498909e547d9cb240
    Image:         registry.k8s.io/sig-storage/csi-snapshotter:v6.2.2
    Image ID:      registry.k8s.io/sig-storage/csi-snapshotter@sha256:becc53e25b96573f61f7469923a92fb3e9d3a3781732159954ce0d9da07233a2
    Port:          <none>
    Host Port:     <none>
    Args:
      --v=2
      --csi-address=$(ADDRESS)
      --leader-election-namespace=nfs-provisioner
      --leader-election
      --timeout=1200s
    State:          Running
      Started:      Wed, 18 Oct 2023 17:26:30 +0700
    Ready:          True
    Restart Count:  0
    Limits:
      memory:  200Mi
    Requests:
      cpu:     10m
      memory:  20Mi
    Environment:
      ADDRESS:  /csi/csi.sock
    Mounts:
      /csi from socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-fgqfl (ro)
  liveness-probe:
    Container ID:  containerd://8e6b34b4a9af7a67c6187bcfeed4d3860dc9bd086fbaf76671fdd684e36701ff
    Image:         registry.k8s.io/sig-storage/livenessprobe:v2.10.0
    Image ID:      registry.k8s.io/sig-storage/livenessprobe@sha256:4dc0b87ccd69f9865b89234d8555d3a614ab0a16ed94a3016ffd27f8106132ce
    Port:          <none>
    Host Port:     <none>
    Args:
      --csi-address=/csi/csi.sock
      --probe-timeout=3s
      --health-port=29652
      --v=2
    State:          Running
      Started:      Wed, 18 Oct 2023 17:26:31 +0700
    Ready:          True
    Restart Count:  0
    Limits:
      memory:  100Mi
    Requests:
      cpu:        10m
      memory:     20Mi
    Environment:  <none>
    Mounts:
      /csi from socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-fgqfl (ro)
  nfs:
    Container ID:  containerd://232a27d29fea2d180cead5df514a0272d5259e5e33a948f32dd78b90bff37cd4
    Image:         registry.k8s.io/sig-storage/nfsplugin:v4.4.0
    Image ID:      registry.k8s.io/sig-storage/nfsplugin@sha256:971cb526bc0108cca7d8efda32102629cb362f99bbd4879fd381bea1b2014ab4
    Port:          29652/TCP
    Host Port:     29652/TCP
    Args:
      --v=5
      --nodeid=$(NODE_ID)
      --endpoint=$(CSI_ENDPOINT)
      --drivername=nfs.csi.k8s.io
      --mount-permissions=0
      --working-mount-dir=/tmp
      --default-ondelete-policy=delete
    State:          Running
      Started:      Wed, 18 Oct 2023 17:26:31 +0700
    Ready:          True
    Restart Count:  0
    Limits:
      memory:  200Mi
    Requests:
      cpu:     10m
      memory:  20Mi
    Liveness:  http-get http://:healthz/healthz delay=30s timeout=10s period=30s #success=1 #failure=5
    Environment:
      NODE_ID:        (v1:spec.nodeName)
      CSI_ENDPOINT:  unix:///csi/csi.sock
    Mounts:
      /csi from socket-dir (rw)
      /tmp from tmp-dir (rw)
      /var/lib/kubelet/pods from pods-mount-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-fgqfl (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  pods-mount-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubelet/pods
    HostPathType:  Directory
  socket-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  tmp-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  kube-api-access-fgqfl:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              kubernetes.io/os=linux
Tolerations:                 node-role.kubernetes.io/control-plane:NoSchedule op=Exists
                             node-role.kubernetes.io/controlplane:NoSchedule op=Exists
                             node-role.kubernetes.io/master:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:                      <none>
```

```
kubectl -n nfs-provisioner logs csi-nfs-controller-59b69c85cc-j554z
I1018 10:26:30.381271       1 feature_gate.go:249] feature gates: &{map[]}
I1018 10:26:30.381486       1 csi-provisioner.go:154] Version: v3.5.0
I1018 10:26:30.381509       1 csi-provisioner.go:177] Building kube configs for running in cluster...
I1018 10:26:32.539444       1 common.go:111] Probing CSI driver for readiness
I1018 10:26:32.545542       1 csi-provisioner.go:230] Detected CSI driver nfs.csi.k8s.io
I1018 10:26:32.549209       1 csi-provisioner.go:302] CSI driver does not support PUBLISH_UNPUBLISH_VOLUME, not watching VolumeAttachments
I1018 10:26:32.549961       1 controller.go:732] Using saving PVs to API server in background
I1018 10:26:32.550493       1 leaderelection.go:245] attempting to acquire leader lease nfs-provisioner/nfs-csi-k8s-io...
I1018 10:26:51.204680       1 leaderelection.go:255] successfully acquired lease nfs-provisioner/nfs-csi-k8s-io
I1018 10:26:51.204845       1 leader_election.go:178] became leader, starting
I1018 10:26:51.305147       1 volume_store.go:97] Starting save volume queue
I1018 10:26:51.305146       1 clone_controller.go:66] Starting CloningProtection controller
I1018 10:26:51.305267       1 clone_controller.go:82] Started CloningProtection controller
I1018 10:26:51.305162       1 controller.go:811] Starting provisioner controller nfs.csi.k8s.io_k3s-hq-master1_f5ea6737-c967-4f12-8420-a380ca702653!
I1018 10:26:51.407009       1 controller.go:860] Started provisioner controller nfs.csi.k8s.io_k3s-hq-master1_f5ea6737-c967-4f12-8420-a380ca702653!

```

**Reply by andyzhangx** [reply]
what's the logs of `kubectl -n nfs-provisioner logs csi-nfs-controller-59b69c85cc-j554z -c nfs`

**Reply by jackchuong** [reply]
```
kubectl -n nfs-provisioner logs csi-nfs-controller-59b69c85cc-j554z -c nfs
I1018 10:26:31.770171       1 nfs.go:76] Driver: nfs.csi.k8s.io version: v4.4.0
I1018 10:26:31.770505       1 nfs.go:115]
DRIVER INFORMATION:
-------------------
Build Date: "2023-06-07T11:31:40Z"
Compiler: gc
Driver Name: nfs.csi.k8s.io
Driver Version: v4.4.0
Git Commit: ""
Go Version: go1.19
Platform: linux/amd64

Streaming logs below:
I1018 10:26:31.779790       1 mount_linux.go:284] Detected umount with safe 'not mounted' behavior
I1018 10:26:31.783311       1 server.go:117] Listening for connections on address: &net.UnixAddr{Name:"//csi/csi.sock", Net:"unix"}
I1018 10:26:31.956218       1 utils.go:106] GRPC call: /csi.v1.Identity/GetPluginInfo
I1018 10:26:31.956248       1 utils.go:107] GRPC request: {}
I1018 10:26:31.958503       1 utils.go:113] GRPC response: {"name":"nfs.csi.k8s.io","vendor_version":"v4.4.0"}
I1018 10:26:31.960368       1 utils.go:106] GRPC call: /csi.v1.Controller/ControllerGetCapabilities
I1018 10:26:31.960397       1 utils.go:107] GRPC request: {}
I1018 10:26:31.960459       1 utils.go:113] GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":13}}},{"Type":{"Rpc":{"type":7}}},{"Type":{"Rpc":{"type":5}}}]}
I1018 10:26:32.350124       1 utils.go:106] GRPC call: /csi.v1.Identity/GetPluginInfo
I1018 10:26:32.350166       1 utils.go:107] GRPC request: {}
I1018 10:26:32.350254       1 utils.go:113] GRPC response: {"name":"nfs.csi.k8s.io","vendor_version":"v4.4.0"}
I1018 10:26:32.545041       1 utils.go:106] GRPC call: /csi.v1.Identity/GetPluginInfo
I1018 10:26:32.545071       1 utils.go:107] GRPC request: {}
I1018 10:26:32.545154       1 utils.go:113] GRPC response: {"name":"nfs.csi.k8s.io","vendor_version":"v4.4.0"}
I1018 10:26:32.545901       1 utils.go:106] GRPC call: /csi.v1.Identity/GetPluginCapabilities
I1018 10:26:32.545925       1 utils.go:107] GRPC request: {}
I1018 10:26:32.546037       1 utils.go:113] GRPC response: {"capabilities":[{"Type":{"Service":{"type":1}}}]}
I1018 10:26:32.548100       1 utils.go:106] GRPC call: /csi.v1.Controller/ControllerGetCapabilities
I1018 10:26:32.548147       1 utils.go:107] GRPC request: {}
I1018 10:26:32.548246       1 utils.go:113] GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":13}}},{"Type":{"Rpc":{"type":7}}},{"Type":{"Rpc":{"type":5}}}]}
```

**Reply by andyzhangx** [reply]
@jackchuong there are multiple nfs controller replicas, the above logs shows this replica is an idle pod. could you get logs of other replica?

**Reply by jackchuong** [reply]
there is only 1 nfs controllder replica
```
kubectl -n nfs-provisioner get pod
NAME                                   READY   STATUS    RESTARTS   AGE
snapshot-controller-7c47788447-z4qlv   1/1     Running   0          17h
csi-nfs-node-6bs56                     3/3     Running   0          17h
csi-nfs-controller-59b69c85cc-j554z    4/4     Running   0          17h
```

**Comment by jackchuong** [comment]
What is exactly detail steps to snapshot a pvc and restore another pvc (at different namespace or cluster) from it ?
I created a snapshot from pvc
```
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: ocs-snapshot
  namespace: ocs-inventory
spec:
  volumeSnapshotClassName: csi-nfs-snapclass
  source:
    persistentVolumeClaimName: ocs-pvc

kubectl -n ocs-inventory get volumesnapshot,volumesnapshotcontent
NAME                                                  READYTOUSE   SOURCEPVC   SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAPSHOTCLASS       SNAPSHOTCONTENT                                    CREATIONTIME   AGE
volumesnapshot.snapshot.storage.k8s.io/ocs-snapshot   true         ocs-pvc                             208190461     csi-nfs-snapclass   snapcontent-e9b061a7-d8db-4ccb-97de-def18f548c6a   7m21s          8m17s

NAME                                                                                                  READYTOUSE   RESTORESIZE   DELETIONPOLICY   DRIVER           VOLUMESNAPSHOTCLASS   VOLUMESNAPSHOT     VOLUMESNAPSHOTNAMESPACE   AGE
volumesnapshotcontent.snapshot.storage.k8s.io/snapcontent-e9b061a7-d8db-4ccb-97de-def18f548c6a        true         208190461     Delete           nfs.csi.k8s.io   csi-nfs-snapclass     ocs-snapshot       ocs-inventory             8m16s
```

It created a folder "snapshot-e9b061a7-d8db-4ccb-97de-def18f548c6a" with file "pvc-4ff12ffb-e929-4862-8500-078d13041d1c.tar.gz" size 200MB in nfs share.
I clone above folder to "snapshot-e9b061a7-d8db-4ccb-97de-def18f548c6a-copy" including file "pvc-4ff12ffb-e929-4862-8500-078d13041d1c.tar.gz" inside.

I try to create pre-provisioned volumesnapshotcontent
```
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  name: snapcontent-e9b061a7-d8db-4ccb-97de-def18f548c6a-copy
spec:
  deletionPolicy: Delete
  driver: nfs.csi.k8s.io
  source:
    snapshotHandle: 192.168.7.107#k8s-nfs-sgnnas03#snapshot-e9b061a7-d8db-4ccb-97de-def18f548c6a-copy#snapshot-e9b061a7-d8db-4ccb-97de-def18f548c6a-copy#pvc-4ff12ffb-e929-4862-8500-078d13041d1c
  volumeSnapshotClassName: csi-nfs-snapclass
  volumeSnapshotRef:
    apiVersion: snapshot.storage.k8s.io/v1
    kind: VolumeSnapshot
    name: restore-snapshot
    namespace: restore
```
But it doesn't work (RESTORESIZE=0)
```
kubectl -n ocs-inventory get volumesnapshot,volumesnapshotcontent
NAME                                                  READYTOUSE   SOURCEPVC   SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAPSHOTCLASS       SNAPSHOTCONTENT                                    CREATIONTIME   AGE
volumesnapshot.snapshot.storage.k8s.io/ocs-snapshot   true         ocs-pvc                             208190461     csi-nfs-snapclass   snapcontent-e9b061a7-d8db-4ccb-97de-def18f548c6a   15m            16m

NAME                                                                                                  READYTOUSE   RESTORESIZE   DELETIONPOLICY   DRIVER           VOLUMESNAPSHOTCLASS   VOLUMESNAPSHOT     VOLUMESNAPSHOTNAMESPACE   AGE
volumesnapshotcontent.snapshot.storage.k8s.io/snapcontent-e9b061a7-d8db-4ccb-97de-def18f548c6a        true         208190461     Delete           nfs.csi.k8s.io   csi-nfs-snapclass     ocs-snapshot       ocs-inventory             16m
volumesnapshotcontent.snapshot.storage.k8s.io/snapcontent-e9b061a7-d8db-4ccb-97de-def18f548c6a-copy   true         0             Delete           nfs.csi.k8s.io   csi-nfs-snapclass     restore-snapshot   restore                   10m
```
