### DISCUSSION TITLE
How to define the name of the PV on the NFS directory after dynamically creating PV using PVC

### DISCUSSION THREAD

**Discussion by caijinhu123** [kubernetes-csi/csi-driver-nfs#548] [Q&A] [answered]
pvc.yaml
`apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-dynamic
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-csi`
After creating PVC using the above YAML, the name of the PV on the NFS directory is
pvc-5a900a0e-506b-470f-b1de-03a021fb44b6

How to set up the display of the directory name on NFS after creating PVC 
default-pvc-nfs-dynamic-470f-b1de-03a021fb44b6  （PVC.namespace-.PVC.name）

**Comment by caijinhu123** [comment]
When defining the storage class, add the 'subDir' parameter, just like the example below
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
...
  subDir: ${pvc.metadata.namespace}-${pvc.metadata.name}-${pv.metadata.name}
reclaimPolicy: Delete
volumeBindingMode: Immediate
``` 
After modifying the storage class, redeployment is required, so that the directory name in NFS will change after creating the PVC.
default-pvc-deployment-nfs-pvc-0593c8ae-a48e-4a2c-86ce-c1156dc91ad4
