### DISCUSSION TITLE
NFS server IP address changes - what should I do ?

### DISCUSSION THREAD

**Discussion by jackchuong** [kubernetes-csi/csi-driver-nfs#774] [Q&A]
Hi all,
I deployed csi-driver-nfs using helm to handle storage in a internal k8s cluster , NFS server is a QNAP device.
I need to change IP address of QNAP device, here my storageclass yaml
```
---
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storageclass-csi-nfs-sgnnas03
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: nfs.csi.k8s.io
parameters:
  server: "192.168.7.107"
  share: /k8s-nfs-sgnnas03
  # csi.storage.k8s.io/provisioner-secret is only needed for providing mountOptions in DeleteVolume
  # csi.storage.k8s.io/provisioner-secret-name: "mount-options"
  # csi.storage.k8s.io/provisioner-secret-namespace: "default"
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1
---
```

I didn't use FQDN for server (my mistake) , what should I do if I need to change nfs server IP address to another ?
If I change it and upgrade helm chart, would it work ? What happen with existed PVC and PV ?
I don't want my data to be lost or corrupted. Please give me some advice, thank you very much.
