### DISCUSSION TITLE
PV not getting created when PVC has dataSource and dataSourceRef keys

### DISCUSSION THREAD

**Discussion by ALL-SPACE-Anas** [kubernetes-csi/csi-driver-nfs#930] [Q&A] [answered]
Hi,

Very new to using CSI drivers and just deployed csi-driver-nfs to OKD4.15 baremetal cluster. Deployed it to dynamically provision pvs for virtual machines via kubevirt. It is working just fine for most part.

Now, in kubevirt, when I try to upload a VM image file to add a boot volume, it creates a corresponding pvc to hold the image. This particular pvc doesn't get bound by csi-driver-nfs as no pv gets created for it.

Looking at the logs of `csi-nfs-controller` pod, I see the following:

```
I0619 17:23:52.317663 1 event.go:389] "Event occurred" object="kubevirt-os-images/rockylinux-8.9" fieldPath="" kind="PersistentVolumeClaim" apiVersion="v1" type="Normal" reason="Provisioning" message="External provisioner is provisioning volume for claim \"kubevirt-os-images/rockylinux-8.9\""
I0619 17:23:52.317635 1 event.go:377] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"kubevirt-os-images", Name:"rockylinux-8.9", UID:"0a65020e-e87d-4392-a3c7-2ea4dae4acbb", APIVersion:"v1", ResourceVersion:"347038325", FieldPath:""}): type: 'Normal' reason: 'Provisioning' Assuming an external populator will provision the volume
```

Looking online and asking AI, I find the reason for this to be dataSource and dataSourceRef keys in pvcs. Apparently they're saying to csi-driver-nfs that another driver will be provisioning the volume for this. I've confirmed that the pvcs that bound successfully don't have dataSource and dataSourceRef defined.

This is the spec for the pvc that gets created by the boot volume widget in kubevirt:

```
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: '34087042032'
  storageClassName: okd-kubevirt-sc
  volumeMode: Filesystem
  dataSource:
    apiGroup: cdi.kubevirt.io
    kind: VolumeUploadSource
    name: volume-upload-source-d2b31bc9-4bab-4cef-b7c4-599c4b6619e1
  dataSourceRef:
    apiGroup: cdi.kubevirt.io
    kind: VolumeUploadSource
    name: volume-upload-source-d2b31bc9-4bab-4cef-b7c4-599c4b6619e1
```

Now, being very new to this, I'm lost as to how to fix this. Really appreciate any help I can get in how this can be resolved. Please let me know if I need to provide any more info.

Cheers,
