### ISSUE TITLE
Support "Ephemeral" volumes

### ISSUE THREAD

**Issue by jhoblitt** [kubernetes-csi/csi-driver-nfs#211]
The builtin nfs storage driver can now be used for "ephemeral" volumes in a pod spec without either an sc or pvc is needed.  E.g.:

```yaml
spec:
  volumes:
    - name: foo
      nfs:
        path: /foo
        server: rook-ceph-nfs-jfoo-a.rook-ceph.svc.cluster.local
```

It would be very convenient if the nfs csi driver could be used in a similar way. E.g.:

```yaml
spec:
  volumes:
    - name: foo
      csi:
        driver: nfs.csi.k8s.io
        volumeAttributes:
          server: rook-ceph-nfs-foo-a.rook-ceph.svc.cluster.local
          share: /foo
```

Attempting this with the current csi driver will fail with:

```
... volume mode "Ephemeral" not supported by driver nfs.csi.k8s.io (only supports ["Persistent"])
```

**Comment by andyzhangx** [comment]
there is a discussion here that we don't want to support Ephemeral Inline Volume for this driver:
https://github.com/kubernetes-csi/csi-driver-nfs/pull/153#issuecomment-849429143

**Comment by jhoblitt** [comment]
Doh. I checked closed issues but not PR.  For my use case, the NFS exports are persistent and shared between many pods.  It seems a bit heavy weight to have to manage a PVC per mount when the PVC isn't infact doing anything.

Trying to follow the discussion in the PR and the link mail list... is the line volume syntax supposed to work if the `Generic Ephemeral Inline Volumes` feature gate is enabled or is that just the planned direction for this driver?

**Comment by andyzhangx** [comment]
Generic Ephemeral Inline Volumes is already supported(beta) in k8s 1.21, e.g.
```
      volumes:
        - name: nfs
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 10Gi
                storageClassName: nfs-csi
```

While the volume lifecycle is same as pod, it's Ephemeral, not exactly identical to original nfs inline volume:
```
spec:
  volumes:
    - name: foo
      nfs:
        path: /foo
        server: rook-ceph-nfs-jfoo-a.rook-ceph.svc.cluster.local
```
