### ISSUE TITLE
VolumeSnapshot path

### ISSUE THREAD

**Issue by saif-88** [kubernetes-csi/csi-driver-nfs#459]
**What happened**:

When i create a VolumeSnapshot the path in the nfs server contain the full path of the PersistentVolume
PersistentVolume path : /mnt/nfs/pvc-xxxxxx
VolumeSnapshot path /mnt/nfs/mnt/nfs/snapcontent-xxxxxx

**What you expected to happen**:

VolumeSnapshot path /mnt/nfs/snapcontent-xxxxxx

**How to reproduce it**:
```yaml
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: snapshot-csi
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
driver: nfs.csi.k8s.io
deletionPolicy: Delete
parameters:
  server: xxxxxx
  share: "/mnt/nfs"
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: snapshot-test
spec:
  source:
    persistentVolumeClaimName: pvc-test
```

**Anything else we need to know?**:

**Environment**:

- CSI Driver version: 4.3.0
- Kubernetes version (use `kubectl version`): 1.26.5 (v1.26.5+rke2r1)
- OS (e.g. from /etc/os-release): Debian 11.5
- Kernel (e.g. `uname -a`): 5.10.0-19-amd64
- Install tools:
- Others:
