### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by hunghip95** [kubernetes-csi/csi-driver-nfs#468]
I'm using helm to generate pv when install new chart.

**The storageclass has parameter:**
````
Name:            nfs-csi
IsDefaultClass:  No
Annotations:     kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"nfs-csi"},"mountOptions":["hard","nfsvers=4.1"],"parameters":{"server":"10.0.9.55","share":"/data","subDir":"${pvc.metadata.name}"},"provisioner":"nfs.csi.k8s.io","reclaimPolicy":"Delete","volumeBindingMode":"Immediate"}

Provisioner:           nfs.csi.k8s.io
Parameters:            server=10.0.9.55,share=/data
AllowVolumeExpansion:  <unset>
MountOptions:
  hard
  nfsvers=4.1
ReclaimPolicy:      Delete
VolumeBindingMode:  Immediate
Events:             <none>
````

**The csi driver is:**
````
root@master-01:~/test-heml-chart# kubectl describe csidrivers nfs.csi.k8s.io 
Name:         nfs.csi.k8s.io
Namespace:    
Labels:       <none>
Annotations:  <none>
API Version:  storage.k8s.io/v1
Kind:         CSIDriver
Metadata:
  Creation Timestamp:  2023-03-29T17:00:28Z
  Managed Fields:
    API Version:  storage.k8s.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        f:attachRequired:
        f:fsGroupPolicy:
        f:podInfoOnMount:
        f:requiresRepublish:
        f:storageCapacity:
        f:volumeLifecycleModes:
          .:
          v:"Persistent":
    Manager:         kubectl-client-side-apply
    Operation:       Update
    Time:            2023-03-29T17:00:28Z
  Resource Version:  248597
  UID:               e00b8e32-0711-41d2-b1a9-552182f683b7
Spec:
  Attach Required:     false
  Fs Group Policy:     File
  Pod Info On Mount:   false
  Requires Republish:  false
  Storage Capacity:    false
  Volume Lifecycle Modes:
    Persistent
Events:  <none>

````

**pv.yaml template:**
````
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistence.pv.name }}
  labels:
    name: {{ .Values.persistence.pv.name }}
spec:
  capacity:
    storage: {{ .Values.persistence.pv.size }}
  accessModes:
    - {{ .Values.persistence.pv.accessMode }}
  storageClassName: {{ .Values.persistence.pv.storageClass }}
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: 10.0.9.55#data#test-fe-2-pv#
    volumeAttributes:
      csi.storage.k8s.io/pv/name: {{ .Values.persistence.pv.name }}
      csi.storage.k8s.io/pvc/name: {{ .Values.persistence.name }}
      csi.storage.k8s.io/pvc/namespace: default
      server: 10.0.9.55
      share: /data
      subDir: {{ .Values.persistence.pv.name }}
      auto-create-path: "true"
      storage.kubernetes.io/csiProvisionerIdentity: "{{ randAlphaNum 13 }}-{{ randNumeric 4 }}-nfs.csi.k8s.io"
      subPath: {{ .Values.persistence.pv.name }}
  volumeMode: Filesystem
  mountOptions:
  - hard
  - nfsvers=4.1
````

**After install helm chart, K8s creates a PV:**
````
root@master-01:~/test-heml-chart# kubectl describe pv test-fe-2-log-pv
Name:            test-fe-2-log-pv
Labels:          app.kubernetes.io/managed-by=Helm
                 name=test-fe-2-log-pv
Annotations:     meta.helm.sh/release-name: test-fe-2
                 meta.helm.sh/release-namespace: default
                 pv.kubernetes.io/bound-by-controller: yes
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:    nfs-csi
Status:          Bound
Claim:           default/test-fe-2-log-pvc
Reclaim Policy:  Retain
Access Modes:    RWO
VolumeMode:      Filesystem
Capacity:        10Gi
Node Affinity:   <none>
Message:         
Source:
    Type:              CSI (a Container Storage Interface (CSI) volume source)
    Driver:            nfs.csi.k8s.io
    FSType:            
    VolumeHandle:      10.0.9.55#data#test-fe-2-pv#
    ReadOnly:          false
    VolumeAttributes:      auto-create-path=true
                           csi.storage.k8s.io/pv/name=test-fe-2-log-pv
                           csi.storage.k8s.io/pvc/name=test-fe-2-log-pvc
                           csi.storage.k8s.io/pvc/namespace=default
                           server=10.0.9.55
                           share=/data
                           storage.kubernetes.io/csiProvisionerIdentity=AYZiqsVK2QJOP-4975-nfs.csi.k8s.io
                           subDir=test-fe-2-log-pv
                           subPath=test-fe-2-log-pv
Events:                <none>
````

**The problem is pod shows No such file or directory error:**

````
root@master-01:~/test-heml-chart# kubectl describe pod test-fe-2-55f8b4b468-pglh6 
Name:             test-fe-2-55f8b4b468-pglh6
Namespace:        default
Priority:         0
Service Account:  default
Node:             worker-03/10.0.9.83
Start Time:       Mon, 26 Jun 2023 15:42:57 +0700
Labels:           app.kubernetes.io/instance=test-fe-2
                  app.kubernetes.io/name=test-fe-2
                  pod-template-hash=55f8b4b468
Annotations:      <none>
Status:           Pending
IP:               
IPs:              <none>
Controlled By:    ReplicaSet/test-fe-2-55f8b4b468
Containers:
  htp-tmp:
    Container ID:   
    Image:          10.0.9.71:5000/test-fe:deploy-k8s-c08870a
    Image ID:       
    Port:           8080/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /data/api/log from test-fe-2-log-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-wgvxb (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  test-fe-2-log-volume:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  test-fe-2-log-pvc
    ReadOnly:   false
  kube-api-access-wgvxb:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason       Age                   From               Message
  ----     ------       ----                  ----               -------
  Normal   Scheduled    16m                   default-scheduler  Successfully assigned default/test-fe-2-55f8b4b468-pglh6 to worker-03
  Warning  FailedMount  3m8s (x3 over 7m40s)  kubelet            Unable to attach or mount volumes: unmounted volumes=[test-fe-2-log-volume], unattached volumes=[kube-api-access-wgvxb test-fe-2-log-volume]: timed out waiting for the condition
  Warning  FailedMount  52s (x4 over 14m)     kubelet            Unable to attach or mount volumes: unmounted volumes=[test-fe-2-log-volume], unattached volumes=[test-fe-2-log-volume kube-api-access-wgvxb]: timed out waiting for the condition
  Warning  FailedMount  4s (x9 over 16m)      kubelet            MountVolume.SetUp failed for volume "test-fe-2-log-pv" : rpc error: code = Internal desc = mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t nfs -o hard,nfsvers=4.1 10.0.9.55:/data/test-fe-2-log-pv /var/lib/kubelet/pods/11b5ab76-8bb9-4219-ac6e-e52ea7c74013/volumes/kubernetes.io~csi/test-fe-2-log-pv/mount
Output: mount.nfs: mounting 10.0.9.55:/data/test-fe-2-log-pv failed, reason given by server: No such file or directory

````

It keeps  _No such file or directory_ error even when I use subDir property.
