### ISSUE TITLE
imagePullSecrets missing from snapshot controller

### ISSUE THREAD

**Issue by dvyas1** [kubernetes-csi/csi-driver-nfs#472]
**What happened**:
`csi-driver-nfs` helm chart fails to install fully when using private registry csi-snapshot-controller image. The imagePullSecrets stub is not present in  `/csi-driver-nfs/templates/csi-snapshot-controller.yaml`, therefore kubernetes fails to pull snapshot controller image from private registry.

**What you expected to happen**:
Kubernetes should be able to pull snapshot controller image from private registry.

**How to reproduce it**:
- Specific info about private registry in values.yaml of the helm chart.
```    
    externalSnapshotter:
        repository: your-private-registry/snapshot-controller
        tag: v6.2.2
        pullPolicy: IfNotPresent
```

- Specify imagePullSecrets in values.yaml of the helm chart.
```
imagePullSecrets:
  - name: your-secret
```
- Install the helm chart and you will notice the snapshot controller pod errors out with image failed to pull.

**Anything else we need to know?**:
This bug only impacts helm chart.

**Environment**:

- CSI Driver version: 4.4.0
- Kubernetes version (use `kubectl version`): 1.24.0
- OS (e.g. from /etc/os-release): Ubuntu 20.04.5 LTS
- Kernel (e.g. `uname -a`): Linux minikube 5.15.90.1-microsoft-standard-WSL2 
- Install tools:
- Others:
