### ISSUE TITLE
How to snapshot/restore static pv/pvc ?

### ISSUE THREAD

**Issue by jackchuong** [kubernetes-csi/csi-driver-nfs#508]
Hi all,
With dynamic PVC I can clone it or snapshot and restore it successfully.
But with static PV/PVC like this
```
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
  name: static-pv-test
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: storageclass-csi-nfs-sgnnas03
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    # volumeHandle format: {nfs-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: 192.168.7.107#k8s-nfs-sgnnas03#test
    volumeAttributes:
      server: 192.168.7.107
      share: /k8s-nfs-sgnnas03
      subdir: test
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: static-pvc-test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: static-pv-test
  storageClassName: storageclass-csi-nfs-sgnnas03

kubectl get pvc,pv
NAME                                     STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                    AGE
persistentvolumeclaim/static-pvc-test    Bound    static-pv-test                             10Gi       RWX            storageclass-csi-nfs-sgnnas03   133m

NAME                                                                           CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                                                          STORAGECLASS                    REASON   AGE
persistentvolume/static-pv-test                                                10Gi       RWX            Retain           Bound    default/static-pvc-test                                                        storageclass-csi-nfs-sgnnas03            133m
```

How can I created a snapshot for it ? I tried
```
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  name: static-pvc-test-snapshotcontent
spec:
  deletionPolicy: Delete
  driver: nfs.csi.k8s.io
  source:
    volumeHandle: 192.168.7.107#k8s-nfs-sgnnas03#test##
  volumeSnapshotClassName: csi-nfs-snapclass
  volumeSnapshotRef:
    apiVersion: snapshot.storage.k8s.io/v1
    kind: VolumeSnapshot
    name: static-pvc-test-snapshot
    namespace: default
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: static-pvc-test-snapshot
spec:
  volumeSnapshotClassName: csi-nfs-snapclass
  source:
    volumeSnapshotContentName: static-pvc-test-snapshotcontent
```

But volumesnapshot and volumesnapshotcontent's READYTOUSE are not true
```
kubectl get volumesnapshot,volumesnapshotcontent
NAME                                                               READYTOUSE   SOURCEPVC          SOURCESNAPSHOTCONTENT             RESTORESIZE   SNAPSHOTCLASS       SNAPSHOTCONTENT                                    CREATIONTIME   AGE
volumesnapshot.snapshot.storage.k8s.io/static-pvc-test-snapshot    false                           static-pvc-test-snapshotcontent                 csi-nfs-snapclass                                                                     8s

NAME                                                                                             READYTOUSE   RESTORESIZE   DELETIONPOLICY   DRIVER           VOLUMESNAPSHOTCLASS   VOLUMESNAPSHOT              VOLUMESNAPSHOTNAMESPACE   AGE
volumesnapshotcontent.snapshot.storage.k8s.io/static-pvc-test-snapshotcontent                    false                      Delete           nfs.csi.k8s.io   csi-nfs-snapclass     static-pvc-test-snapshot    default                   8s

kubectl describe volumesnapshot.snapshot.storage.k8s.io/static-pvc-test-snapshot
Name:         static-pvc-test-snapshot
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  snapshot.storage.k8s.io/v1
Kind:         VolumeSnapshot
Metadata:
  Creation Timestamp:  2023-09-26T06:57:03Z
  Generation:          1
  Resource Version:    2012282
  UID:                 d29355d2-0df5-4e63-acd4-f77708d3e52d
Spec:
  Source:
    Volume Snapshot Content Name:  static-pvc-test-snapshotcontent
  Volume Snapshot Class Name:      csi-nfs-snapclass
Status:
  Error:
    Message:     VolumeSnapshotContent is dynamically provisioned while expecting a pre-provisioned one
    Time:        2023-09-26T06:57:03Z
  Ready To Use:  false
Events:
  Type     Reason                   Age                  From                 Message
  ----     ------                   ----                 ----                 -------
  Warning  SnapshotContentMismatch  2m45s                snapshot-controller  VolumeSnapshotContent is dynamically provisioned while expecting a pre-provisioned one
  Warning  SnapshotFinalizerError   40s (x8 over 2m45s)  snapshot-controller  Failed to check and update snapshot: snapshot default/static-pvc-test-snapshot expects a pre-provisioned VolumeSnapshotContent static-pvc-test-snapshotcontent but gets a dynamically provisioned one

kubectl describe volumesnapshotcontent.snapshot.storage.k8s.io/static-pvc-test-snapshotcontent
Name:         static-pvc-test-snapshotcontent
Namespace:
Labels:       <none>
Annotations:  snapshot.storage.kubernetes.io/volumesnapshot-being-created: yes
API Version:  snapshot.storage.k8s.io/v1
Kind:         VolumeSnapshotContent
Metadata:
  Creation Timestamp:  2023-09-26T06:57:03Z
  Generation:          1
  Resource Version:    2012284
  UID:                 b1d9e0c7-2908-413c-a333-dc33c9111b80
Spec:
  Deletion Policy:  Delete
  Driver:           nfs.csi.k8s.io
  Source:
    Volume Handle:             192.168.7.107#k8s-nfs-sgnnas03#test##
  Volume Snapshot Class Name:  csi-nfs-snapclass
  Volume Snapshot Ref:
    API Version:  snapshot.storage.k8s.io/v1
    Kind:         VolumeSnapshot
    Name:         static-pvc-test-snapshot
    Namespace:    default
Status:
  Error:
    Message:     Failed to check and update snapshot content: failed to take snapshot of the volume 192.168.7.107#k8s-nfs-sgnnas03#test##: "cannot create snapshot. Snapshot content static-pvc-test-snapshotcontent not bound to a snapshot"
    Time:        2023-09-26T06:57:03Z
  Ready To Use:  false
Events:
  Type     Reason                               Age    From                            Message
  ----     ------                               ----   ----                            -------
  Warning  SnapshotCreationFailed               3m15s  csi-snapshotter nfs.csi.k8s.io  Failed to create snapshot: failed to take snapshot of the volume 192.168.7.107#k8s-nfs-sgnnas03#test##: "cannot create snapshot. Snapshot content static-pvc-test-snapshotcontent not bound to a snapshot"
  Warning  SnapshotContentCheckandUpdateFailed  3m15s  csi-snapshotter nfs.csi.k8s.io  Failed to check and update snapshot content: failed to take snapshot of the volume 192.168.7.107#k8s-nfs-sgnnas03#test##: "cannot create snapshot. Snapshot content static-pvc-test-snapshotcontent not bound to a snapshot"
```

**Comment by andyzhangx** [comment]
you only need to define `VolumeSnapshot` like this, not necessary to set other fields, e.g. `volumeSnapshotRef`

https://github.com/kubernetes-csi/csi-driver-nfs/blob/master/deploy/example/snapshot-nfs-dynamic.yaml

**Comment by jackchuong** [comment]
Please note I'm trying to snapshot a static PV/PVC , not dynamic PVC (dynamic one works fine)
If I just create `VolumeSnapshot` like this
```
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: static-pvc-test-snapshot
spec:
  volumeSnapshotClassName: csi-nfs-snapclass
  source:
    persistentVolumeClaimName: static-pvc-test
```

It still not work
```
kubectl get pvc,pv,volumesnapshot,volumesnapshotcontent
NAME                                     STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                    AGE
persistentvolumeclaim/static-pvc-test    Bound    static-pv-test                             10Gi       RWX            storageclass-csi-nfs-sgnnas03   3h4m

NAME                                                                           CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                                                          STORAGECLASS                    REASON   AGE
persistentvolume/static-pv-test                                                10Gi       RWX            Retain           Bound    default/static-pvc-test                                                        storageclass-csi-nfs-sgnnas03            3h4m

NAME                                                               READYTOUSE   SOURCEPVC          SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAPSHOTCLASS       SNAPSHOTCONTENT                                    CREATIONTIME   AGE
volumesnapshot.snapshot.storage.k8s.io/static-pvc-test-snapshot    false        static-pvc-test                                          csi-nfs-snapclass   snapcontent-a7735ff5-dcac-48b8-a518-be2ed49b2061                  6s

NAME                                                                                             READYTOUSE   RESTORESIZE   DELETIONPOLICY   DRIVER           VOLUMESNAPSHOTCLASS   VOLUMESNAPSHOT              VOLUMESNAPSHOTNAMESPACE   AGE
volumesnapshotcontent.snapshot.storage.k8s.io/snapcontent-a7735ff5-dcac-48b8-a518-be2ed49b2061   false                      Delete           nfs.csi.k8s.io   csi-nfs-snapclass     static-pvc-test-snapshot    default                   5s

kubectl describe volumesnapshot.snapshot.storage.k8s.io/static-pvc-test-snapshot
Name:         static-pvc-test-snapshot
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  snapshot.storage.k8s.io/v1
Kind:         VolumeSnapshot
Metadata:
  Creation Timestamp:  2023-09-26T07:44:36Z
  Finalizers:
    snapshot.storage.kubernetes.io/volumesnapshot-as-source-protection
    snapshot.storage.kubernetes.io/volumesnapshot-bound-protection
  Generation:        1
  Resource Version:  2017467
  UID:               a7735ff5-dcac-48b8-a518-be2ed49b2061
Spec:
  Source:
    Persistent Volume Claim Name:  static-pvc-test
  Volume Snapshot Class Name:      csi-nfs-snapclass
Status:
  Bound Volume Snapshot Content Name:  snapcontent-a7735ff5-dcac-48b8-a518-be2ed49b2061
  Error:
    Message:     Failed to check and update snapshot content: failed to take snapshot of the volume nfs-server.default.svc.cluster.local/share##: "rpc error: code = NotFound desc = failed to create nfsSnapshot: missing required source volume name"
    Time:        2023-09-26T07:44:37Z
  Ready To Use:  false
Events:
  Type    Reason            Age    From                 Message
  ----    ------            ----   ----                 -------
  Normal  CreatingSnapshot  3m28s  snapshot-controller  Waiting for a snapshot default/static-pvc-test-snapshot to be created by the CSI driver.

kubectl describe volumesnapshotcontent.snapshot.storage.k8s.io/snapcontent-a7735ff5-dcac-48b8-a518-be2ed49b2061
Name:         snapcontent-a7735ff5-dcac-48b8-a518-be2ed49b2061
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  snapshot.storage.k8s.io/v1
Kind:         VolumeSnapshotContent
Metadata:
  Creation Timestamp:  2023-09-26T07:44:37Z
  Finalizers:
    snapshot.storage.kubernetes.io/volumesnapshotcontent-bound-protection
  Generation:        1
  Resource Version:  2018393
  UID:               53c77e7e-39f5-4dec-a7fc-a287c97c1485
Spec:
  Deletion Policy:  Delete
  Driver:           nfs.csi.k8s.io
  Source:
    Volume Handle:             nfs-server.default.svc.cluster.local/share##
  Volume Snapshot Class Name:  csi-nfs-snapclass
  Volume Snapshot Ref:
    API Version:       snapshot.storage.k8s.io/v1
    Kind:              VolumeSnapshot
    Name:              static-pvc-test-snapshot
    Namespace:         default
    Resource Version:  2017439
    UID:               a7735ff5-dcac-48b8-a518-be2ed49b2061
Status:
  Error:
    Message:     Failed to check and update snapshot content: failed to take snapshot of the volume nfs-server.default.svc.cluster.local/share##: "rpc error: code = NotFound desc = failed to create nfsSnapshot: missing required source volume name"
    Time:        2023-09-26T07:44:37Z
  Ready To Use:  false
Events:
  Type     Reason                               Age    From                            Message
  ----     ------                               ----   ----                            -------
  Warning  SnapshotCreationFailed               3m58s  csi-snapshotter nfs.csi.k8s.io  Failed to create snapshot: failed to take snapshot of the volume nfs-server.default.svc.cluster.local/share##: "rpc error: code = NotFound desc = failed to create nfsSnapshot: missing required source volume name"
  Warning  SnapshotContentCheckandUpdateFailed  3m58s  csi-snapshotter nfs.csi.k8s.io  Failed to check and update snapshot content: failed to take snapshot of the volume nfs-server.default.svc.cluster.local/share##: "rpc error: code = NotFound desc = failed to create nfsSnapshot: missing required source volume name"
```

**Comment by andyzhangx** [comment]
since you already have the working one (with dynamic provisioning), you could  create a static pv referencing to the dynamic pv, ideally static or dynamic pv does no difference.

**Comment by jackchuong** [comment]
I don't really understand you.
If I create a static PV like this
```
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
  name: static-pv-test
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: storageclass-csi-nfs-sgnnas03
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    # volumeHandle format: {nfs-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: 192.168.7.107#k8s-nfs-sgnnas03#test
    volumeAttributes:
      server: 192.168.7.107
      share: /k8s-nfs-sgnnas03
      subdir: test
```

Then I create a PVC like this
```
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: static-pvc-test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: storageclass-csi-nfs-sgnnas03
```

Then PVC `static-pvc-test` is bound to PV `static-pv-test` automatically , yes
```
kubectl get pvc,pv
NAME                                     STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                    AGE
persistentvolumeclaim/static-pvc-test    Bound    static-pv-test                             10Gi       RWX            storageclass-csi-nfs-sgnnas03   73s

NAME                                                                           CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                                                          STORAGECLASS                    REASON   AGE
persistentvolume/static-pv-test                                                10Gi       RWX            Retain           Bound    default/static-pvc-test                                                        storageclass-csi-nfs-sgnnas03            73s
```

But VolumeSnapshot `static-pvc-test-snapshot` doesn't work
```
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: static-pvc-test-snapshot
spec:
  volumeSnapshotClassName: csi-nfs-snapclass
  source:
    persistentVolumeClaimName: static-pvc-test

kubectl get volumesnapshot,volumesnapshotcontent
NAME                                                               READYTOUSE   SOURCEPVC          SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAPSHOTCLASS       SNAPSHOTCONTENT                                    CREATIONTIME   AGE
volumesnapshot.snapshot.storage.k8s.io/static-pvc-test-snapshot    false        static-pvc-test                                          csi-nfs-snapclass   snapcontent-9d1b1ee2-a866-4f00-a194-d5321b9f38d3                  8s

NAME                                                                                             READYTOUSE   RESTORESIZE   DELETIONPOLICY   DRIVER           VOLUMESNAPSHOTCLASS   VOLUMESNAPSHOT              VOLUMESNAPSHOTNAMESPACE   AGE
volumesnapshotcontent.snapshot.storage.k8s.io/snapcontent-9d1b1ee2-a866-4f00-a194-d5321b9f38d3   false                      Delete           nfs.csi.k8s.io   csi-nfs-snapclass     static-pvc-test-snapshot    default                   7s

kubectl describe volumesnapshot.snapshot.storage.k8s.io/static-pvc-test-snapshot
Name:         static-pvc-test-snapshot
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  snapshot.storage.k8s.io/v1
Kind:         VolumeSnapshot
Metadata:
  Creation Timestamp:  2023-09-26T08:43:44Z
  Finalizers:
    snapshot.storage.kubernetes.io/volumesnapshot-as-source-protection
    snapshot.storage.kubernetes.io/volumesnapshot-bound-protection
  Generation:        1
  Resource Version:  2025375
  UID:               9d1b1ee2-a866-4f00-a194-d5321b9f38d3
Spec:
  Source:
    Persistent Volume Claim Name:  static-pvc-test
  Volume Snapshot Class Name:      csi-nfs-snapclass
Status:
  Bound Volume Snapshot Content Name:  snapcontent-9d1b1ee2-a866-4f00-a194-d5321b9f38d3
  Error:
    Message:     Failed to check and update snapshot content: failed to take snapshot of the volume 192.168.7.107#k8s-nfs-sgnnas03#test: "rpc error: code = Internal desc = failed to mount snapshot nfs server: rpc error: code = Internal desc = mkdir /tmp/snapshot-9d1b1ee2-a866-4f00-a194-d5321b9f38d3: read-only file system"
    Time:        2023-09-26T08:43:45Z
  Ready To Use:  false
Events:
  Type    Reason            Age   From                 Message
  ----    ------            ----  ----                 -------
  Normal  CreatingSnapshot  30s   snapshot-controller  Waiting for a snapshot default/static-pvc-test-snapshot to be created by the CSI driver.

kubectl describe volumesnapshotcontent.snapshot.storage.k8s.io/snapcontent-9d1b1ee2-a866-4f00-a194-d5321b9f38d3
Name:         snapcontent-9d1b1ee2-a866-4f00-a194-d5321b9f38d3
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  snapshot.storage.k8s.io/v1
Kind:         VolumeSnapshotContent
Metadata:
  Creation Timestamp:  2023-09-26T08:43:45Z
  Finalizers:
    snapshot.storage.kubernetes.io/volumesnapshotcontent-bound-protection
  Generation:        1
  Resource Version:  2025569
  UID:               affb201c-d56d-497c-9f7a-84e25a2cf555
Spec:
  Deletion Policy:  Delete
  Driver:           nfs.csi.k8s.io
  Source:
    Volume Handle:             192.168.7.107#k8s-nfs-sgnnas03#test
  Volume Snapshot Class Name:  csi-nfs-snapclass
  Volume Snapshot Ref:
    API Version:       snapshot.storage.k8s.io/v1
    Kind:              VolumeSnapshot
    Name:              static-pvc-test-snapshot
    Namespace:         default
    Resource Version:  2025351
    UID:               9d1b1ee2-a866-4f00-a194-d5321b9f38d3
Status:
  Error:
    Message:     Failed to check and update snapshot content: failed to take snapshot of the volume 192.168.7.107#k8s-nfs-sgnnas03#test: "rpc error: code = Internal desc = failed to mount snapshot nfs server: rpc error: code = Internal desc = mkdir /tmp/snapshot-9d1b1ee2-a866-4f00-a194-d5321b9f38d3: read-only file system"
    Time:        2023-09-26T08:43:45Z
  Ready To Use:  false
Events:
  Type     Reason                               Age   From                            Message
  ----     ------                               ----  ----                            -------
  Warning  SnapshotCreationFailed               50s   csi-snapshotter nfs.csi.k8s.io  Failed to create snapshot: failed to take snapshot of the volume 192.168.7.107#k8s-nfs-sgnnas03#test: "rpc error: code = Internal desc = failed to mount snapshot nfs server: rpc error: code = Internal desc = mkdir /tmp/snapshot-9d1b1ee2-a866-4f00-a194-d5321b9f38d3: read-only file system"
  Warning  SnapshotContentCheckandUpdateFailed  50s   csi-snapshotter nfs.csi.k8s.io  Failed to check and update snapshot content: failed to take snapshot of the volume 192.168.7.107#k8s-nfs-sgnnas03#test: "rpc error: code = Internal desc = failed to mount snapshot nfs server: rpc error: code = Internal desc = mkdir /tmp/snapshot-9d1b1ee2-a866-4f00-a194-d5321b9f38d3: read-only file system"
```
