### ISSUE TITLE
add e2e test for this driver

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-csi/csi-driver-nfs#51]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

Option#1, re-enable https://github.com/kubernetes-csi/csi-driver-nfs#running-kubernetes-end-to-end-tests-on-an-nfs-driver

Option#2 as below:

### 1. Install nfs-server-provisioner helm chart
 - following example would provision 100GB storage(one data disk) on an agent node, serving as a NFSv3 server
```console
helm repo add stable https://kubernetes-charts.storage.googleapis.com/
helm install stable/nfs-server-provisioner --generate-name --set=persistence.storageClass=default,persistence.enabled=true,persistence.size=100Gi
```

### 2. get nfs server address, in following example, it's `10.0.193.57:/export`
```console
# k get svc
NAME                                TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)                                                                                                     AGE
nfs-server-provisioner-1599984974   ClusterIP   10.0.193.57   <none>        2049/TCP,2049/UDP,32803/TCP,32803/UDP,20048/TCP,20048/UDP,875/TCP,875/UDP,111/TCP,111/UDP,662/TCP,662/UDP   46m
```

### 3. set nfs address in PV:
```yaml
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: data-id
    volumeAttributes:
      # The nfs server could be a K8s service
      # server: nfs-server.default.svc.cluster.local
      server: 10.0.193.57
      share: /export
```

### 4. create nginx example pod
```console
# k exec -it nginx sh
# mount | grep nfs
10.0.193.57:/export on /var/www type nfs4 (rw,relatime,vers=4.2,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=10.244.0.145,local_lock=none,addr=10.0.193.57)
```

refer to https://github.com/kubernetes-csi/csi-driver-nfs/blob/master/examples/kubernetes/nginx.yaml

**Describe alternatives you've considered**

**Additional context**
