### ISSUE TITLE
Pod with PVC provisioned by csi-driver-nfs fails to start due to FailedMount with error `mkdir /var/snap: read-only file system`

### ISSUE THREAD

**Issue by chheller** [kubernetes-csi/csi-driver-nfs#514]
**What happened**:
Using dynamic provisioning, after mounting a PV to an NFS share on my TrueNAS server, pods fail to start with the reason `FailedMount` and the following error
```
MountVolume.SetUp failed for volume "pvc-63f0962b-5970-4d1a-b8df-35322e0d5dc7" : rpc error: code = Internal desc = mkdir /var/snap: read-only file system
```
**What you expected to happen**:
The pod should be able to start normally
**How to reproduce it**:
Using a fresh microk8s installation, on Ubuntu server, against an NFS share provisioned with TrueNAS

The TrueNAS NFS share is configured simply with NFSv4 enabled, and NFSv3 ownership model for NFSv4

Commands to install the driver and storage class
```sh
# Install NFS CSI
helm upgrade --install -n kube-system csi-driver-nfs csi-driver-nfs/csi-driver-nfs --version v4.4.0 --set linux.kubelet="/var/snap/microk8s/common/var/lib/kubelet" --set controller.replicas=1 --set feature.enableFSGroupPolicy=true 
kc apply -f ~/k8s/nfs/nfs.storageclass.yaml
kubectl patch storageclass csi-driver-nfs -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
```
<details open>
  <summary>nfs.storageclass.yaml</summary>

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-driver-nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.1.200 # Fill in your own server details
  share: /mnt/Primary/kubernetes/csi-driver-nfs
  subdir: /${pvc.metadata.namespace}/${pvc.metadata.name}
  mountPermissions: '0777'
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
```

</details>
Using the democratic-csi zfs-nfs csi driver, I do not face these same issues. Notably, however, I do face some issues where the containers lack the permissions to `chown` or `chmod` files or directories in mounted directories. There aren't any specific restrictions on the NAS, I've tried to configure to be as loosely permissioned as possible to prevent these issues. I've tried as many options and configurations as I can think to try with the storage class, pod securityContexts, and NFS settings to no avail. Also worth noting is that I was successfully using the csi-driver-nfs with volume mounts on NAS successfully for the last 6 months or so, but recently took down my cluster and re-installed it from scratch. In doing so, I likely upgraded the version of the csi-driver-nfs which may be responsible, but have not had time to try and reverse engineer which version of the driver I might have been using previously. 

**Environment**:

- CSI Driver version:` helm.sh/chart: csi-driver-nfs-v4.4.0`
- Kubernetes version:
```
Client Version: v1.27.5
Kustomize Version: v5.0.1
Server Version: v1.27.5
```
- OS (e.g. from /etc/os-release): `Ubuntu 22.04.3 LTS`
- Kernel: `Linux homelab 5.15.0-86-generic #96-Ubuntu SMP Wed Sep 20 08:23:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: `Microk8s 1.27.5`
- Others
  - `TrueNAS 13.0-U5.3`
