### ISSUE TITLE
VolumeFailedDelete, when i deleted pvc but pv wasn't deleted

### ISSUE THREAD

**Issue by liuyuexizhi** [kubernetes-csi/csi-driver-nfs#595]
Warning  VolumeFailedDelete  7s (x5 over 22s)  nfs.csi.k8s.io_linux-k8s-master-2_c99df0ef-f12f-40a3-998f-f99dbc758a17  rpc error: code = Internal desc = archive subdirectory(/tmp/pvc-ee9206d9-a4fc-4897-93ab-0bb3f25c893a/default/test-busybox-pvc, /tmp/pvc-ee9206d9-a4fc-4897-93ab-0bb3f25c893a/archived-default/test-busybox-pvc) failed with rename /tmp/pvc-ee9206d9-a4fc-4897-93ab-0bb3f25c893a/default/test-busybox-pvc /tmp/pvc-ee9206d9-a4fc-4897-93ab-0bb3f25c893a/archived-default/test-busybox-pvc: no such file or directory

**Comment by liuyuexizhi** [comment]
it seams archive subdirectory after umount operator. 

sc yaml:
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: 56-nfs-sc
provisioner: nfs.csi.k8s.io
parameters:
  server: "xxx.xxx.xxx.xxx"
  share: "/vol1/k8s"
  subDir: "${pvc.metadata.namespace}/${pvc.metadata.name}"
  mountPermissions: "0"
  onDelete: "archive"
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - nfsvers=3
  - rsize=1048576
  - wsize=1048576
  - tcp
  - hard
  - nolock
```
pvc yaml
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc-nfs-dynamic
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: 56-nfs-sc
```

can somebody help me?

**Comment by liuyuexizhi** [comment]
the new info：
**when do not  set subDir, it work!**

sc yaml：
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: 56-nfs-sc
provisioner: nfs.csi.k8s.io
parameters:
  server: "172.16.40.56"
  share: "/vol1/k8s"
  #subDir: "${pvc.metadata.namespace}/${pvc.metadata.name}"
  mountPermissions: "0"
  onDelete: "archive"
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - nfsvers=3
  - rsize=1048576
  - wsize=1048576
  - tcp
  - hard
  - nolock
```

**Comment by andyzhangx** [comment]
so archive mode with subDir set does not work, right? @liuyuexizhi

**Comment by liuyuexizhi** [comment]
> so archive mode with subDir set does not work, right? @liuyuexizhi

yes, it do not work with subDir set！

**Comment by liuyuexizhi** [comment]
@andyzhangx hi, i find a new question.
i can not expand pvc, i had set `allowVolumeExpansion: true` for storageCalss.
```text
  Normal   ExternalProvisioning   7m5s (x2 over 7m5s)  persistentvolume-controller                                             waiting for a volume to be created, either by external provisioner "nfs.csi.k8s.io" or manually created by system administrator
  Normal   Provisioning           7m5s                 nfs.csi.k8s.io_linux-k8s-master-3_365b3c6f-b74a-493b-9058-6ee923c437ce  External provisioner is provisioning volume for claim "default/test-pvc-nfs-dynamic"
  Normal   ProvisioningSucceeded  7m5s                 nfs.csi.k8s.io_linux-k8s-master-3_365b3c6f-b74a-493b-9058-6ee923c437ce  Successfully provisioned volume pvc-ff340d9e-8d99-4dda-8d4f-93d132e20765
  Warning  ExternalExpanding      6m40s                volume_expand                                                           Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC.
```
do you know something?

**Comment by liuyuexizhi** [comment]
**`and else, I can not limit pvc storage!!!`**

**Comment by andyzhangx** [comment]
this driver does not support pvc expansion

**Comment by andyzhangx** [comment]
> > so archive mode with subDir set does not work, right? @liuyuexizhi
> 
> yes, it do not work with subDir set！

@liuyuexizhi if you set `subDir: "${pvc.metadata.namespace}-${pvc.metadata.name}"`, it should work.

**Comment by MRColorR** [comment]
hello, i'm having the same issue but my subdir contains hypens: 

- event from kubectl describe pv <pvname>: `Warning  VolumeFailedDelete  3m44s (x13 over 21m)  nfs.csi.k8s.io_kube-master.test.intranet_3e1b5747-bd74-4af1-a568-e28fc997d6e3  rpc error: code = Internal desc = archive subdirectory(/tmp/pvc-3df3470d-60ba-4f12-9517-bfcf25884ddc/coder-coder-mrengo-test-sidecar-home-pvc-3df3470d-60ba-4f12-9517-bfcf25884ddc, /tmp/pvc-3df3470d-60ba-4f12-9517-bfcf25884ddc/archived-coder-coder-mrengo-test-sidecar-home-pvc-3df3470d-60ba-4f12-9517-bfcf25884ddc) failed with rename /tmp/pvc-3df3470d-60ba-4f12-9517-bfcf25884ddc/coder-coder-mrengo-test-sidecar-home-pvc-3df3470d-60ba-4f12-9517-bfcf25884ddc /tmp/pvc-3df3470d-60ba-4f12-9517-bfcf25884ddc/archived-coder-coder-mrengo-test-sidecar-home-pvc-3df3470d-60ba-4f12-9517-bfcf25884ddc: no such file or directory`

- my storage class is the following:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: nfs.csi.k8s.io
parameters:
  server: kube-nfs
  share: /shared/pv_nfs-csi-k8s-io
  # csi.storage.k8s.io/provisioner-secret is only needed for providing mountOptions in DeleteVolume
  # csi.storage.k8s.io/provisioner-secret-name: "mount-options"
  # csi.storage.k8s.io/provisioner-secret-namespace: "default"
  subDir: ${pvc.metadata.namespace}-${pvc.metadata.name}-${pv.metadata.name}
  onDelete: archive
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
```
- i'm using csi-driver-nfs v4.8.0 installed using helm with following parameters: `helm upgrade --install csi-driver-nfs csi-driver-nfs/csi-driver-nfs --namespace kube-system --set externalSnapshotter.enabled=true --set controller.runOnControlPlane=true`
