### ISSUE TITLE
pvc pending status  Waiting for a volume to be created either by the external provisioner

### ISSUE THREAD

**Issue by mansoncui** [kubernetes-csi/csi-driver-nfs#682]
kubevirt dv import image pvc pending
kubectl describe pvc pvc-name error info :
```
Assuming an external populator will provision the volume
 Normal  ExternalProvisioning         9s (x8 over 64s)   persistentvolume-controller                                                     
Waiting for a volume to be created either by the external provisioner 'nfs.csi.k8s.io' or manually by the system administrator. If volume creation is delayed, please verify that the provisioner is running and correctly registered.
```
kubevirt dv http upload image yaml file:
```
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: img-cirros
spec:
  source:
    http:
      url: http://10.2.xx.xx/images/cirros-0.5.1-x86_64-disk.img 
  pvc:
    storageClassName: "nfs-client"
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 1Gi
```

- CSI Driver version: v4.7.0
- Kubernetes version (use `kubectl version`): 1.28.2
- OS (e.g. from /etc/os-release): centos7.3
- Kernel (e.g. `uname -a`): 5.4.153-1.el7.elrepo.x86_64
- Install tools:  
- Others:
