### ISSUE TITLE
Helm Chart should create VolumeSnapshotClass as well.

### ISSUE THREAD

**Issue by rbo** [kubernetes-csi/csi-driver-nfs#825]
**Is your feature request related to a problem?/Why is this needed**

If you deploy csi-driver-nfs with:
```yaml
externalSnapshotter:
  enabled: true
```

It should roll out an VolumeSnapshotClass as well.

```yaml
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: csi-nfs-snapclass
driver: nfs.csi.k8s.io
deletionPolicy: Delete
```

As described in the deployment: https://github.com/kubernetes-csi/csi-driver-nfs/blob/master/deploy/example/snapshot/snapshotclass-nfs.yaml

**Describe the solution you'd like in detail**

**Describe alternatives you've considered**

**Additional context**
