### ISSUE TITLE
helm version should be "semver 2" (e.g. 4.10.0 instead of v4.10.0)

### ISSUE THREAD

**Issue by ymettier** [kubernetes-csi/csi-driver-nfs#851]
# What happened

Helm chart version is `vX.Y.Z`. Example : `v4.10.0`

See section "Anything else we need to know" why I complain.

# What you expected to happen

Helm chart version should be `X.Y.Z`. Example : `4.10.0`.

Reason is explained here : https://helm.sh/docs/topics/charts/#the-chartyaml-file

> version: A SemVer 2 version (required)

# Anything else we need to know?

Disclaimer : I'm not sure my problem is related to this issue.

I'm using Flux and, in my HelmRelease, I wrote this:

```
...
  chart:
    spec:
      chart: "csi-driver-nfs"
      version: '^v4.9.0'
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
...
```

However Flux tries to install v4.10.0, ignoring my `'^v4.9.0'.

As described in the Flux documentation https://fluxcd.io/flux/guides/helmreleases/#using-a-chart-template the version should be compatible with semver there too:

> The `.chart.spec.version` can be a fixed semver, or any semver range (i.e. >=4.0.0 <5.0.0). 

Will this issue fix my problem ? No idea. However it may fix it.

In any case, even if it does not fix my problem, the version of the chart should follow semver 2 as explained in the helm doc (see the link at the beginning of the issue).

# Environment

N/A
